config/routes.rb
Rails.application.routes.draw do

  root "artists#index"
  root "songs#index"

  resources :artists
  resources :songs


end



  # get 'artists/index'
  # get 'artists/show'
  # get 'artists/delete'
  #
  # get 'songs/index'
  # get 'songs/show'
  # get 'songs/new'
  # get 'songs/delete'
  #
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  # get "artists" => "artists#index"
  # get "songs" => "songs#index"
  # get "artists/:id" => "artists#show", as: :artist
  # get "songs/:id" => "songs#show", as: :song
  #
  # post "songs" => "songs#create"
  #
  # delete "artists/:id" => "artists#destroy"
  # delete "songs/:id" => "songs#destroy"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :songs, dependent: :destroy

    def self.order_by_name
      order(:name)
    end



end

app/models/song.rb
class Song < ApplicationRecord


  belongs_to :artist


  validates :genre, presence: true
  validates :song_name, presence: true
  validates :song_url, presence: true, length: { maximum: 500 }

  # def self.order_by_name
  #   order(:song_name)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController



  def index

    @artists = Artist.order_by_name
    # @artist = Artist.new
  end

  def show
    @artist = Artist.find(params[:id])
    # @song = Song.new(:artist_id => @artist.id) (may be this should be done now)

  end

  # def new
  #   @artist = Artist.new({:name => 'Default'})
  # end

  # def create
  #   # Instantiate a new object using form parameters
  #   @artist = Artist.new(artist_params)
  #   # Save the object
  #   if @artist.save
  #     # If save succeeds, redirect to the index action
  #     flash[:notice] = "artist created successfully."
  #     redirect_to(artists_path)
  #   else
  #     # If save fails, redisplay the form so user can fix problems
  #     render('new')
  #   end
  # end

  # def edit
  #   @artist = artist.find(params[:id])
  # end

  def update
    # Find a new object using form parameters
    @artist = artist.find(params[:id])
    # Update the object
    if @artist.update_attributes(artist_params)
      # If save succeeds, redirect to the show action
      flash[:notice] = "Artist updated successfully."
      redirect_to(artist_path(@artist))
    else
      # If save fails, redisplay the form so user can fix problems
      render('edit')
    end
  end

  # def delete
  #   @artist = artist.find(params[:id])
  # end

  def destroy
    @artist = artist.find(params[:id])
    @artist.destroy
    flash[:notice] = "artist destroyed successfully."
    redirect_to(artists_path)
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :age, :nationality, :image_url)
  end



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    before_action :find_artist

    # def index
    #   @songs = @artist.songs
    #   @song = Song.new(:artist_id => @artist.id)
    # end
    #
    # def show
    #   @song = Song.find(params[:id])
    # end


    def index
         @song = Song.new
         @songs =@artist.songs

       format.html { redirect_to songs_path(:artist_id => @artist.id) }
       format.json { render :index, status: :list, location: @artist.id }

    end

    def show
      @song = Song.find(params[:id])
      format.html { redirect_to songs_path(:artist_id => @artist.id) }
      format.json { render :show, status: :list, location: @artist.id }
    end

    def new
      @song = Song.new(:artist_id => @artist.id)
    end

    def create
        @song = Song.new(song_params)
        @song.artist = @artist
        respond_to do |format|
          if @song.save
            format.html { redirect_to songs_path(:artist_id => @artist.id), notice: 'Song was successfully created.' }
            format.json { render :show, status: :created, location: @song }
          else
            format.html { redirect_to songs_path(:artist_id => @artist.id)}
            format.json { render json: @song.errors, status: :unprocessable_entity }
          end
        end
      end


    def destroy
      @song = Song.find(params[:id])
      @song.destroy
      format.html { redirect_to songs_path(:artist_id => @artist.id), notice: 'Song was successfully deleted.' }
      format.json { render :delete, status: :deleted, location: @song }

    end

    private

      def song_params
        params
        .require(:song)
        .permit(:genre, :song_name, :duration, :song_url, :artist_id)
     end



    def find_artist
      @artist = Artist.find(params[:artist_id])
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<div class="Artists index">
  <h2>Ethiopian Artists</h2>


  <%= link_to("Add New Artist", new_artist_path, :class => 'action new') %>

  <table class="listing" summary="Artist list">
    <tr class="header">

      <th>Artist</th>
      <th>Age</th>
      <th>Nationality</th>

      <th>Actions</th>
    </tr>
    <% @artists.each do |artist| %>
    <tr>

      <td><%= artist.name %></td>
      <td><%= artist.age %></td>
      <td><%= artist.nationality %></td>

      <td class="actions">
        <%= link_to("View Songs", songs_path(:artist_id => artist.id), :class => 'action show') %>
        <%= link_to("Show", artist_path(artist), :class => 'action show') %>

      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/artists/show.html.erb
<% @song_title = "Show Artist" %>
<%= link_to("<< Back to List", artists_path, :class => 'back-link') %>

<div class="artists show">
  <h2>Detail of Artist</h2>

  <table summary=" Detail Artist view">
    <tr>
      <th>Name</th>
      <td><%= @artist.name %></td>
    </tr>
    <tr>
      <th>Age</th>
      <td><%= @artist.age %></td>
    </tr>
    <tr>
      <th>nationality</th>
      <td><%= @artist.nationality %></td>
    </tr>
    <tr>
      <th>Photo</th>
      <td><%=image_tag @artist.image_url %></td>
    </tr>

  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= yield %>

    <br><br>
    <hr>

    <%= link_to "[All Artists]", root_path %>

  </body>
</html>

app/views/songs/_form.html.erb
<div class="fsongoup">
  <label>Song name:</label>
  <%= f.text_field :song_name, placeholder: "Song title", class: "form-control", id:"songnameInput" %>

  <div class="form-group">
    <label>Genre:</label>
    <%= f.text_field :genre, placeholder: "hip hop", class: "form-control", id: "genreInput" %>
  </div>

<hr>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-danger", id: "add_songname" %>
    <%= link_to "Back", artist_path(@artist), class: "btn btn-default" %>
 </div>
</div>

app/views/songs/index.html.erb
<div class="Songs index">
<h2>Songs</h2>
<div class="align-image">
  <div class="panel-heading">
    <%= link_to("Add New Song", new_song_path(:artist_id => @artist.id), :class => 'action new') %>
  </div>
  <div class ="panel-body">
  <table id="songlist">
    <% @songs.each do |song| %>
    <tr>
        <td><%= song.song_name%></td>
        <td><%= song.genre%></td>
        <td>
          <%= button_tag "Delete", class: "btn btn-default", id: "deleteSongButton", onclick: 'deleteSong(' + song.artist.id.to_s + ', ' + song.id.to_s + ')' %>
        </td>
        <td class="actions">
          <%= link_to("Show", song_path(song, :artist_id => @artist.id), :class => 'action show') %>
          <%= link_to("Edit", edit_song_path(song, :artist_id => @artist.id), :class => 'action edit') %>
        </td>
    </tr>
      <%end%>
  </table>
  <div>
    <%= link_to "Delete All Songs", song_path(:artist_id => @artist.id), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
  <div class="fsongoup">
    <label>Song Name:</label>
    <input id="songnameInput" type="text" class="form-control" placeholder="Song Name">

    <div class="form-group">
      <label>Genre:</label>
      <input id="genreInput" type="text" class="form-control" placeholder="eg. 03:40">
    </div>
  <hr>
    <div class="actions">
      <%= button_tag "Save Song", class: "btn btn-danger", id: "saveSongButton", onclick: 'addSong(' + @artist.id.to_s + ')' %>
   </div>
  </div>
    <%= link_to "Back to Artists", artists_path, class: "btn btn-default" %>
  </div>
</div>
</div>

app/views/songs/new.html.erb
<% @song_title = "New song" %>

 <%= link_to "<< Back to List", songs_path(:artist_id => @artist.id), :class => 'back-link' %>

 <div class="songs new">
   <h2>Create song</h2>

<%= form_for(@song, :url => songs_path(:artist_id => @artist.id)) do |f| %>

     <%= render(:partial => 'form', :locals => {:f => f}) %>

     <div class="form-buttons">
       <%= f.submit("Create song") %>
     </div>

   <% end %>
 </div>

app/views/songs/show.html.erb
<%= link_to("<< Back to List", songs_path(:artist_id => @artist.id), :class => 'back-link') %>

<div class="Songs show">
  <h2>Show song</h2>

  <table summary="Song detail view">
    <tr>
      <th>Song Name</th>
      <td><%= @song.song_name %></td>
    </tr>
    <tr>
      <th>Song Genre</th>
      <td><%= @song.genre %></td>
    </tr>
  </table>

</div>